# Generated by Django 6.0.5 on 2026-05-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('dairy', 'Dairy'), ('meat', 'Meat & Seafood'), ('produce', 'Produce'), ('grains', 'Grains & Bread'), ('frozen', 'Frozen'), ('canned', 'Canned & Jarred'), ('condiments', 'Condiments & Sauces'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('other', 'Other')], default='other', max_length=50)),
                ('expiry_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('dairy', 'Dairy'), ('meat', 'Meat & Seafood'), ('produce', 'Produce'), ('grains', 'Grains & Bread'), ('frozen', 'Frozen'), ('canned', 'Canned & Jarred'), ('condiments', 'Condiments & Sauces'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('other', 'Other')], default='other', max_length=50)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('purchased', models.BooleanField(default=False)),
                ('original_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_entries', to='pantry.pantryitem')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
